import fs from 'fs';

// Define the list of environment variables to process
const keysToProcess = ['SHOPIFY_API_KEY'];

const envPath = '../.env';

const envString = fs.readFileSync(envPath, 'utf-8');
const envVariables = {};
const lines = envString.trim().split('\n');

lines.forEach(line => {
  const [key, value] = line.split('=');
  if (keysToProcess.includes(key) && value !== undefined) {
    envVariables['VITE_' + key.trim()] = value.trim();
  }
});

fs.writeFileSync('.env', ['// This file was generated by prebuild.js', ...Object.entries(envVariables).map(([key, value]) => `${key}=${value}`)].join('\n'));