import fs from 'fs';
import toml from 'toml';

const envPath = '../.env';
const appPath = '../shopify.app.toml';
const prodAppPath = '../shopify.app.prod.toml';

const envVariables = (() => {
  const envString = fs.readFileSync(envPath, 'utf-8');
  const lines = envString.trim().split('\n');
  const output = {};

  lines.forEach(line => {
    const [key, value] = line.split('=');
    if (value !== undefined) {
      output[key.trim()] = value.trim();
    }
  });

  return output;
})();

const appConfig = (() => {
  const tomlString = fs.readFileSync(appPath, 'utf-8');
  const prodTomlString = fs.readFileSync(prodAppPath, 'utf-8');
  const parsedConfig = toml.parse(tomlString);
  const prodParsedConfig = toml.parse(prodTomlString);
  if (parsedConfig.client_id === envVariables['SHOPIFY_API_KEY']) {
    return parsedConfig;
  } else if (prodParsedConfig.client_id === envVariables['SHOPIFY_API_KEY']) {
    return prodParsedConfig;
  } else {
    throw new Error('SHOPIFY_API_KEY does not match any app configuration');
  }
})();

envVariables['SHOPIFY_APP_HANDLE'] = appConfig.handle;

fs.writeFileSync('.env', ['// This file was generated by prebuild.js', ...Object.entries(envVariables).map(([key, value]) => `VITE_${key}=${value}`)].join('\n'));